import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "media",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // --- Light mode semantic tokens ---
        background: "#f8f9fa",
        "on-background": "#191c1d",
        surface: "#f8f9fa",
        "surface-lowest": "#ffffff",
        "surface-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-high": "#e7e8e9",
        "surface-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#484554",
        "surface-dim": "#d9dadb",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#6042d6",
        outline: "#797586",
        "outline-variant": "#c9c4d7",

        // --- Dark mode semantic tokens (use with dark: prefix) ---
        "d-background": "#0f0f14",
        "d-on-background": "#e7e8eb",
        "d-surface": "#14141b",
        "d-surface-lowest": "#1b1b24",
        "d-surface-low": "#1f1f29",
        "d-surface-container": "#24242f",
        "d-surface-high": "#2c2c38",
        "d-surface-highest": "#353541",
        "d-surface-variant": "#2c2c38",
        "d-on-surface": "#e7e8eb",
        "d-on-surface-variant": "#b7b3c4",
        "d-outline": "#9b95ad",
        "d-outline-variant": "#4a4658",

        // --- Brand / MD3 fixed tokens (same in both modes) ---
        primary: "#451ebb",
        "on-primary": "#ffffff",
        "primary-container": "#5d3fd3",
        "on-primary-container": "#d8ceff",
        "primary-fixed": "#e6deff",
        "primary-fixed-dim": "#cabeff",
        "on-primary-fixed": "#1c0062",
        "on-primary-fixed-variant": "#4723be",
        "inverse-primary": "#cabeff",
        secondary: "#006a67",
        "on-secondary": "#ffffff",
        "secondary-container": "#73f3ef",
        "on-secondary-container": "#006e6c",
        "secondary-fixed": "#76f6f2",
        "secondary-fixed-dim": "#55dad5",
        "on-secondary-fixed": "#00201f",
        "on-secondary-fixed-variant": "#00504e",
        tertiary: "#7b2900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9b3f16",
        "on-tertiary-container": "#ffc8b4",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb599",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#7f2b01",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        unit: "4px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
