import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--bg)",
        "on-background": "var(--on-bg)",
        surface: "var(--surface)",
        "surface-bright": "var(--surface)",
        "surface-dim": "#d9dadb",
        "surface-variant": "var(--surface-variant)",
        "surface-container-lowest": "var(--surface-lowest)",
        "surface-container-low": "var(--surface-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-high)",
        "surface-container-highest": "var(--surface-highest)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#6042d6",
        primary: "#451ebb",
        "on-primary": "#ffffff",
        "primary-container": "#5d3fd3",
        "on-primary-container": "#d8ceff",
        "primary-fixed": "#e6deff",
        "primary-fixed-dim": "#cabeff",
        "on-primary-fixed": "#1c0062",
        "on-primary-fixed-variant": "#4723be",
        "inverse-primary": "#cabeff",
        secondary: "#006a67",
        "on-secondary": "#ffffff",
        "secondary-container": "#73f3ef",
        "on-secondary-container": "#006e6c",
        "secondary-fixed": "#76f6f2",
        "secondary-fixed-dim": "#55dad5",
        "on-secondary-fixed": "#00201f",
        "on-secondary-fixed-variant": "#00504e",
        tertiary: "#7b2900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9b3f16",
        "on-tertiary-container": "#ffc8b4",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb599",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#7f2b01",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        unit: "4px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        "soft-purple": "0 8px 30px rgba(93, 63, 211, 0.08)",
        "soft-purple-md": "0 8px 30px rgba(93, 63, 211, 0.05)",
        "soft-purple-lg": "0 12px 40px rgba(93, 63, 211, 0.3)",
        "nav-up": "0 -8px 30px rgba(93, 63, 211, 0.12)",
        card: "0 4px 20px rgba(0, 0, 0, 0.03)",
      },
    },
  },
  plugins: [],
};

export default config;
