export type ColorId = "primary" | "secondary" | "tertiary" | "neutral";

export type CatalogEntry = {
  template: string;
  name: string;
  description: string;
  icon: string;
  color: ColorId;
  unit: string;
  target: number | null;
  defaultTimes: string[];
};

export const HABIT_CATALOG: CatalogEntry[] = [
  {
    template: "water_intake",
    name: "Drink Water",
    description: "Stay hydrated throughout the day.",
    icon: "water_drop",
    color: "secondary",
    unit: "ml",
    target: 2000,
    defaultTimes: ["08:00", "12:00", "16:00", "20:00"],
  },
  {
    template: "run",
    name: "Run",
    description: "Go for a run to build endurance.",
    icon: "directions_run",
    color: "primary",
    unit: "km",
    target: 5,
    defaultTimes: ["07:00"],
  },
  {
    template: "walk",
    name: "Walk",
    description: "Take a brisk walk every day.",
    icon: "directions_walk",
    color: "tertiary",
    unit: "km",
    target: 3,
    defaultTimes: ["08:00"],
  },
  {
    template: "read",
    name: "Read",
    description: "Read books to grow your mind.",
    icon: "menu_book",
    color: "primary",
    unit: "pages",
    target: 20,
    defaultTimes: ["21:00"],
  },
  {
    template: "meditate",
    name: "Meditate",
    description: "Calm your mind with daily meditation.",
    icon: "self_improvement",
    color: "secondary",
    unit: "min",
    target: 10,
    defaultTimes: ["07:30"],
  },
  {
    template: "journal",
    name: "Journal",
    description: "Reflect and write in your journal.",
    icon: "edit_note",
    color: "primary",
    unit: "",
    target: null,
    defaultTimes: ["22:00"],
  },
  {
    template: "workout",
    name: "Workout",
    description: "Strength training or gym session.",
    icon: "fitness_center",
    color: "tertiary",
    unit: "min",
    target: 45,
    defaultTimes: ["07:00"],
  },
  {
    template: "sleep",
    name: "Sleep 8 hours",
    description: "Get a full night of quality sleep.",
    icon: "bedtime",
    color: "primary",
    unit: "hr",
    target: 8,
    defaultTimes: ["22:30"],
  },
  {
    template: "vitamins",
    name: "Take Vitamins",
    description: "Don't skip your daily supplements.",
    icon: "medication",
    color: "secondary",
    unit: "",
    target: null,
    defaultTimes: ["08:00"],
  },
  {
    template: "healthy_eating",
    name: "Eat Healthy",
    description: "Choose nutritious meals today.",
    icon: "restaurant",
    color: "tertiary",
    unit: "",
    target: null,
    defaultTimes: ["12:00"],
  },
  {
    template: "cold_shower",
    name: "Cold Shower",
    description: "Build discipline with a cold shower.",
    icon: "shower",
    color: "secondary",
    unit: "min",
    target: 3,
    defaultTimes: ["07:00"],
  },
  {
    template: "no_social_media",
    name: "No Social Media",
    description: "Stay off social media for the day.",
    icon: "do_not_disturb_on",
    color: "neutral",
    unit: "",
    target: null,
    defaultTimes: [],
  },
  {
    template: "coding",
    name: "Code",
    description: "Practice coding or work on a project.",
    icon: "code",
    color: "primary",
    unit: "min",
    target: 60,
    defaultTimes: ["10:00"],
  },
  {
    template: "stretch",
    name: "Stretch",
    description: "Improve flexibility with daily stretching.",
    icon: "sports_gymnastics",
    color: "secondary",
    unit: "min",
    target: 15,
    defaultTimes: ["08:00"],
  },
  {
    template: "cycling",
    name: "Cycle",
    description: "Ride your bike for fitness or commute.",
    icon: "directions_bike",
    color: "tertiary",
    unit: "km",
    target: 10,
    defaultTimes: ["07:30"],
  },
  {
    template: "cooking",
    name: "Cook at Home",
    description: "Prepare a healthy home-cooked meal.",
    icon: "outdoor_grill",
    color: "tertiary",
    unit: "",
    target: null,
    defaultTimes: ["18:00"],
  },
];
