import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8f9fa",
        "on-background": "#191c1d",
        surface: "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#6042d6",
        "on-surface": "#191c1d",
        "on-surface-variant": "#484554",
        primary: "#451ebb",
        "primary-container": "#5d3fd3",
        "on-primary": "#ffffff",
        "on-primary-container": "#d8ceff",
        "primary-fixed": "#e6deff",
        "primary-fixed-dim": "#cabeff",
        "inverse-primary": "#cabeff",
        secondary: "#006a67",
        "secondary-container": "#73f3ef",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006e6c",
        "secondary-fixed": "#76f6f2",
        "secondary-fixed-dim": "#55dad5",
        "on-secondary-fixed": "#00201f",
        "on-secondary-fixed-variant": "#00504e",
        tertiary: "#7b2900",
        "tertiary-container": "#9b3f16",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffc8b4",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb599",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#7f2b01",
        outline: "#797586",
        "outline-variant": "#c9c4d7",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        unit: "4px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        gutter: "16px",
      },
      boxShadow: {
        card: "0 4px 24px rgba(93,63,211,0.07)",
        "card-hover": "0 12px 36px rgba(93,63,211,0.13)",
        nav: "0 2px 20px rgba(93,63,211,0.06)",
        cta: "0 8px 28px rgba(93,63,211,0.38)",
        "cta-hover": "0 12px 40px rgba(93,63,211,0.5)",
        sidebar: "4px 0 20px rgba(93,63,211,0.05)",
      },
      keyframes: {
        floatY: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        floatY: "floatY 3s ease-in-out infinite",
        "floatY-delay": "floatY 3s ease-in-out infinite 1.5s",
        fadeInUp: "fadeInUp 0.4s ease forwards",
      },
    },
  },
  plugins: [],
};

export default config;
